Close: "47 setup js linter"
SamReeve96/Acetate-Dissertation-Prototype- pull request #48
Opened 2020-01-30 22:25 UTC by SamReeve96

Added ESLint and custom rules.
Resolved those errors it reported.

Works great with VSCode! 😊

2020-01-30 23:12 UTC, sebj requested changes

2020-01-30 23:12 UTC, sebj commented on extension/background/background.js
> +// set the element of the last right clicked element from the buffer in the
Could capitalise 'set' for consistency here :)

2020-01-30 23:12 UTC, sebj commented on extension/background/background.js
> +    id: 'Annotate Element',
It looks like this menu item ID is checked against on L60 too – can this be pulled out into a constant?

2020-01-30 23:12 UTC, sebj commented on extension/background/background.js
>  // added for debugging storage changes
Minor, but could capitalise for consistency

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
>  function SortAnnotations(redrawAnnotations = true) {
This function name should probably be camelCased for consistency, depending on what rule you've decided on. There are a few other instances across JS files if so

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
>      if (annotationSort === 'Element') {
Could the annotation sort values be pulled out into an object perhaps? It'd reduce the chance of mistyping static strings and possibly give code autocomplete suggestions.

```
const AnnotationSort = {
    ELEMENT: 'Element',
    CREATED: 'Created'
    ...
}
```

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const commentBox = document.querySelector('[annotationId="' + annotationId + '"] textarea');
As these selector queries all share the same prefix, could you extract that out into its own variable?

`const selectorPrefix = '[annotationId="' + annotationId + '"]';`

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
> +        // leaving edit mode
Should probably be capitalised for consistency :)

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const filteredAnnotations = draftAnnotations.filter(annotation => annotation.ID === annotationId);
I think `const annotation = draftAnnotations.find(annotation => annotation.ID === annotationID);` would be more appropriate here, as it will only ever return the single matching element or `undefined`.

The if statement below could act as a guard to return from instead, which would collapse the `else` block.

```
if (annotation === undefined) {
    console.log('No annotation found with ID: ' + annotationId);
    return
}

...
```

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const filteredAnnotations = currentAnnotationInstance.annotations.filter(annotation => annotation.ID === annotationId);
Same feedback as previous around using `.find`, and collapsing the `if-else` applies here I think :)

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const clone = document.importNode(commentBoxTemplate.content, true);
`cloneComment` or `cloneAnnotation` might be a more descriptive variable name here

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
> +    saveButton.addEventListener('click', (annotation) => {
Not sure, but you might be able to collapse this and the following arrow functions down completely by providing the function reference straight away (correct me if I'm wrong!)

Something like:
`saveButton.addEventListener('click', saveAnnotation);`

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/content.js
>          changeTheme();
Not sure if I've understood correctly, but does `changeTheme` toggle back and forth between dark & light modes? Perhaps `toggleTheme` would be a more accurate name if so

2020-01-30 23:12 UTC, sebj commented on .eslintrc.json
> +    "rules": {
I'd highly recommend enabling the [`arrow-parens` rule](https://eslint.org/docs/rules/arrow-parens) – it'll recommend omitting the brackets/parenthesis around the parameters of arrow functions when there's only one parameter.

There's a few instances in your code where it'll clean up the arrow function callbacks even further.

2020-01-30 23:12 UTC, sebj commented on extension/background/background.js
>          type: 'changeContainerState'
Can these message types be pulled out into an object structure to avoid duplication of magic string constants? Could be a separate file, or feel free to ignore if some constants aren't really shared between scripts.

```
const MessageType = {
    CHANGE_CONTAINER_STATE: 'changeContainerState'
}
```

Would also open up the possibility of scoping them even further, basically codifying some of your `Inform content script to ...` comments, although again I'm not entirely familiar with the use-cases:
```

const MessageType = {
   ContentScript: {
         CHANGE_CONTAINER_STATE: 'changeContainerState'
    }
}
```

2020-01-30 23:12 UTC, sebj commented on extension/background/background.js
>          // if there are any instances
Not sure this comment is necessary – the `if` statement condition below the comment is quite readable I'd argue

2020-01-30 23:12 UTC, sebj commented on extension/background/background.js
> +            const filteredInstances = result.annotationInstances.filter(instance => (instance.url === currentInstance.url));
I think `.find(..)` would be more appropriate here, as it'll return either the matching item or `undefined`

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const annotationIsADraft = draftAnnotations.filter(annotation => annotation.ID === annotationId).length === 1;
Previous feedback applies I think – `.find(..)` would be more appropriate here

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
>          annotationTextBox.classList.add('dark');
I wonder if it might be possible to pull out your theming into a object structure, with convenience methods to check if an element is in dark mode/toggle it/whatever your needs

```
const Theme {
    const DARK: 'dark'
    const LIGHT: 'light'

   const getTheme = element => { return element.classList.contains('dark') }
}
```

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
>          // remove dark mode classes
Could capitalise this and the `else` branch comment for consistency

2020-01-30 23:12 UTC, sebj commented on extension/contentScripts/content.js
>          element.setAttribute('element_audit_id', elementCounter);
`element_position_id` might be a more descriptive attribute name from what I've gathered. It might still be worth renaming this function (`markElementPositionIDs`?) and/or adding a documentation comment to it too.

2020-01-30 23:49 UTC, sebj requested changes

2020-01-30 23:49 UTC, sebj commented on extension/options/options.js
> +chrome.storage.sync.get('activeOnPageLoad', (data) => {
`data` could be destructured to simplify this further, which would make the required properties of the input data more explicit when skim-reading:
`chrome.storage.sync.get('activeOnPageLoad', { activeOnPageLoad } => { ...`

(Not sure whether you'd need to use `({ activeOnPageLoad })` instead though)

2020-01-30 23:49 UTC, sebj commented on extension/options/options.js
>      darkModeByDefaultCheckBox.checked = data.darkModeByDefault;
Previous feedback on destructuring applies here too

2020-01-30 23:49 UTC, sebj commented on package.json
> +  "author": "",
Could be filled in while you're here perhaps?

2020-01-30 23:49 UTC, sebj commented on extension/background/background.js
>                  // update instances (remove old instance of url
Closing bracket missing at the end of this line, 'update' could probably be capitalised too

2020-01-30 23:49 UTC, sebj commented on .eslintrc.json
> +    "globals": {
Are these two globals used anywhere in your code, or can they be removed?

2020-01-31 10:29 UTC, sebj commented on .eslintrc.json
> +        "camelcase": [2, {"properties": "never"}],
Really minor, but worth adding spaces inside the options object's braces here

2020-01-31 10:32 UTC, sebj commented on extension/background/background.js
> +        console.log('Storage key "%s" in namespace "%s" changed. ' +
Should be able to replace the `%s` formatters with template literals – ``console.log(`Store key "${key}" in namespace...`)``

2020-01-31 17:42 UTC, SamReeve96 commented on extension/background/background.js
> +// set the element of the last right clicked element from the buffer in the
Resolved in: https://github.com/SamReeve96/Acetate/commit/fd9cbc9e951abc0a4b4ff7a47329d87c11041fd8

2020-01-31 18:02 UTC, SamReeve96 commented on extension/background/background.js
> +    id: 'Annotate Element',
Resolved in: https://github.com/SamReeve96/Acetate/commit/edcf2df51b79e85c1428a7f4b2cf46f3020ca279

2020-01-31 18:04 UTC, SamReeve96 commented on extension/background/background.js
>  // added for debugging storage changes
Just sanity checking, does this refer to the line '// added for debugging...' If so resolved from an earlier commit

2020-01-31 19:05 UTC, sebj commented on extension/background/background.js
>  // added for debugging storage changes
Yep, that's the one :)

2020-01-31 20:52 UTC, sebj commented on extension/contentScripts/content.js
>  function AuditElements() {
Late comment, but what do you think about 'calculateElementPositionIDs' or something similar as a function name here? Trying to think of something a bit more descriptive

2020-01-31 20:56 UTC, SamReeve96 commented on extension/contentScripts/content.js
>  function AuditElements() {
Agreed, will make it a part of https://github.com/SamReeve96/Acetate/issues/49 Plus rename the issue too I guess 😅

2020-01-31 20:56 UTC, sebj commented on extension/contentScripts/content.js
>  function AuditElements() {
Awesome, ok :)

2020-01-31 21:12 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
>  function SortAnnotations(redrawAnnotations = true) {
Done, applied to all other instances I could find (I hope) - https://github.com/SamReeve96/Acetate/commit/4886800c1bce8aef4e392944aaf8a3d8a0c5129b

2020-01-31 21:39 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
>      if (annotationSort === 'Element') {
Resolved in: https://github.com/SamReeve96/Acetate/commit/dcd2239fc4141bc34ff361c959096f0258d031dd

2020-01-31 21:40 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const commentBox = document.querySelector('[annotationId="' + annotationId + '"] textarea');
ooooh good shout, will implement!

2020-01-31 21:51 UTC, sebj commented on extension/contentScripts/commentContainer/commentContainer.js
>      if (annotationSort === 'Element') {
Looking much better! :)

2020-01-31 21:54 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const commentBox = document.querySelector('[annotationId="' + annotationId + '"] textarea');
Resolved in: https://github.com/SamReeve96/Acetate/commit/aa9e3a0c6b61897aff11548539857ba148df4785

2020-02-01 10:43 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
> +        // leaving edit mode
Resolved as of an earlier commit

2020-02-01 17:04 UTC, SamReeve96 commented on extension/background/background.js
> +            const filteredInstances = result.annotationInstances.filter(instance => (instance.url === currentInstance.url));
Resolved by: https://github.com/SamReeve96/Acetate/commit/a28cd1092d54aea079aa487d4a1078829e6618ad

2020-02-01 17:04 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const annotationIsADraft = draftAnnotations.filter(annotation => annotation.ID === annotationId).length === 1;
Also resolved by: https://github.com/SamReeve96/Acetate/commit/a28cd1092d54aea079aa487d4a1078829e6618ad

2020-02-01 17:35 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const filteredAnnotations = draftAnnotations.filter(annotation => annotation.ID === annotationId);
Resolved in: https://github.com/SamReeve96/Acetate/commit/ec7cfedc4a8b4fc59d446d9abc93c0ca846cc88d

2020-02-01 17:35 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const filteredAnnotations = currentAnnotationInstance.annotations.filter(annotation => annotation.ID === annotationId);
Resolved in: https://github.com/SamReeve96/Acetate/commit/ec7cfedc4a8b4fc59d446d9abc93c0ca846cc88d

2020-02-01 17:38 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
> +    const clone = document.importNode(commentBoxTemplate.content, true);
Resolved in: https://github.com/SamReeve96/Acetate/commit/89bd5cc7b9e1ac10464eea782742304ef8764ab6

2020-02-01 17:41 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
> +    saveButton.addEventListener('click', (annotation) => {
Tried out of curiosity but no dice, so will leave this as is.

2020-02-01 17:44 UTC, SamReeve96 commented on extension/contentScripts/content.js
>          changeTheme();
Contemplating dumping any Theme or at least removing this instance and revisiting later. With the new cards UI, there doesnt seem to be much that will be altered by being in Dark or light mode. Let me know what you think.

2020-02-01 17:47 UTC, SamReeve96 commented on .eslintrc.json
> +    "rules": {
Seems the rule actually enforces putting parenthesis around single argument arrow functions?

2020-02-01 17:47 UTC, sebj commented on extension/contentScripts/content.js
>          changeTheme();
That's cool – if you're removing or changing code around themes, then feel free to ignore or come back to this

2020-02-01 17:48 UTC, SamReeve96 commented on .eslintrc.json
> +    "rules": {
My mistake, didnt see the extra setting to add

2020-02-01 17:48 UTC, sebj commented on .eslintrc.json
> +    "rules": {
Even with the `"as-needed"` option? Kinda sounds like that does what we're trying to go for – "enforces no braces where they can be omitted"

2020-02-01 18:14 UTC, SamReeve96 commented on .eslintrc.json
> +    "globals": {
Resolved in: https://github.com/SamReeve96/Acetate/commit/4a9781108bcd21e630876c09e7892bda2c20c320

2020-02-01 18:14 UTC, SamReeve96 commented on .eslintrc.json
> +        "camelcase": [2, {"properties": "never"}],
Resolved in: https://github.com/SamReeve96/Acetate/commit/4a9781108bcd21e630876c09e7892bda2c20c320

2020-02-01 18:34 UTC, SamReeve96 commented on extension/background/background.js
>          // if there are any instances
Removed in an earlier commit

2020-02-01 18:35 UTC, SamReeve96 commented on extension/contentScripts/content.js
>          element.setAttribute('element_audit_id', elementCounter);
Spun out to new issue - https://github.com/SamReeve96/Acetate/issues/49

2020-02-01 18:37 UTC, SamReeve96 commented on extension/background/background.js
>                  // update instances (remove old instance of url
Resolved in earlier commit

2020-02-01 18:38 UTC, SamReeve96 commented on extension/contentScripts/content.js
>          changeTheme();
Think I'll remove/revisit Themes for later, so not going to invest in the time cleaning it up for now, due to more pressing matters. Will spin out to new issue referencing your theme related comments there.

2020-02-01 18:40 UTC, SamReeve96 commented on .eslintrc.json
> +    "rules": {
yep, did miss the as-needed option. Now implemented and working great.

2020-02-01 18:41 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
>          // remove dark mode classes
Done in earlier commit

2020-02-01 18:42 UTC, SamReeve96 commented on extension/contentScripts/content.js
>          changeTheme();
Will look at in the future in - https://github.com/SamReeve96/Acetate/issues/51

2020-02-01 18:44 UTC, SamReeve96 commented on extension/contentScripts/commentContainer/commentContainer.js
>          annotationTextBox.classList.add('dark');
Agreed, I do like this! As I'm still unsure about the future of themes I've referred to this comment in an issue where I'll revisit themes. https://github.com/SamReeve96/Acetate/issues/51

2020-02-01 18:58 UTC, SamReeve96 commented on extension/background/background.js
>          type: 'changeContainerState'
I do agree with the argument made here. I'm not too sure about a separate file as this will make maintenance a bit of a pain in my opinion. I feel the best option is to spin out as an issue and revisit a little later down the line, once adding new messages becomes less frequent.

2020-02-01 19:01 UTC, SamReeve96 commented on extension/background/background.js
>          type: 'changeContainerState'
https://github.com/SamReeve96/Acetate/issues/52

2020-02-01 20:00 UTC, SamReeve96 commented on extension/options/options.js
> +chrome.storage.sync.get('activeOnPageLoad', (data) => {
resolved in: https://github.com/SamReeve96/Acetate/commit/75a2f1f4e61903e260cb64d7322cd36835eab654

2020-02-01 20:00 UTC, SamReeve96 commented on extension/options/options.js
>      darkModeByDefaultCheckBox.checked = data.darkModeByDefault;
Resolved in: https://github.com/SamReeve96/Acetate/commit/75a2f1f4e61903e260cb64d7322cd36835eab654

2020-02-01 20:03 UTC, SamReeve96 commented on package.json
> +  "author": "",
Resolved in: https://github.com/SamReeve96/Acetate/commit/6a9ebfbaeb6986bfeb1fb2fdbd1d4d39dc16a0c9

2020-02-01 20:15 UTC, SamReeve96 commented on extension/background/background.js
> +        console.log('Storage key "%s" in namespace "%s" changed. ' +
Resolved in: https://github.com/SamReeve96/Acetate/commit/ed3023c3c1e33752e3eb3e47d36dc6820acf3452

2020-02-01 20:17 UTC, SamReeve96 commented on extension/background/background.js
> +        console.log('Storage key "%s" in namespace "%s" changed. ' +
Re-resolved: https://github.com/SamReeve96/Acetate/commit/19d930e56d184949bfa6dc5048dd6248432cafac

2020-02-01 20:18 UTC, sebj approved these changes
Looks much better overall! :)

2020-02-01 20:21 UTC, merged